#!/usr/bin/env python3
"""Wrap an MP2 elementary stream in 2,304-byte MPEG Program Stream sectors."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import subprocess
import sys


SECTOR_SIZE = 2304
MP2_BITRATES_MPEG1_LAYER2 = (
    0, 32, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 384,
)
MP2_SAMPLE_RATES_MPEG1 = (44100, 48000, 32000)


def mp2_period_90k(data: bytes) -> int:
    """Return the exact rounded 90 kHz duration of an MPEG-1 Layer II ES."""
    offset = 0
    frame_count = 0
    sample_rate = 0

    while offset < len(data):
        if offset + 4 > len(data):
            raise ValueError("truncated MP2 frame header")
        header = int.from_bytes(data[offset : offset + 4], "big")
        version = (header >> 19) & 0x3
        layer = (header >> 17) & 0x3
        bitrate_index = (header >> 12) & 0xF
        sample_rate_index = (header >> 10) & 0x3
        padding = (header >> 9) & 0x1
        if (header >> 21) != 0x7FF or version != 3 or layer != 2:
            raise ValueError(f"invalid MPEG-1 Layer II frame at byte {offset}")
        if bitrate_index == 0 or bitrate_index == 15 or sample_rate_index == 3:
            raise ValueError(f"invalid MP2 bitrate/sample rate at byte {offset}")

        bitrate = MP2_BITRATES_MPEG1_LAYER2[bitrate_index] * 1000
        this_rate = MP2_SAMPLE_RATES_MPEG1[sample_rate_index]
        if sample_rate and this_rate != sample_rate:
            raise ValueError("MP2 sample rate changes within loop")
        sample_rate = this_rate
        frame_size = (144 * bitrate) // sample_rate + padding
        if offset + frame_size > len(data):
            raise ValueError("truncated MP2 frame")
        offset += frame_size
        frame_count += 1

    if not frame_count:
        raise ValueError("MP2 stream has no frames")
    ticks_numerator = frame_count * 1152 * 90000
    return (ticks_numerator + sample_rate // 2) // sample_rate


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="MP2 elementary stream")
    parser.add_argument("output", type=Path, help="generated C source")
    parser.add_argument("--name", default="lostride_mpg", help="C symbol base for the embedded stream")
    args = parser.parse_args()
    if not args.input.is_file():
        parser.error(f"input does not exist: {args.input}")
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", args.name):
        parser.error("--name must be a C identifier")
    try:
        period_90k = mp2_period_90k(args.input.read_bytes())
    except ValueError as exc:
        parser.error(str(exc))

    result = subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-i", str(args.input),
         "-c:a", "copy", "-muxpreload", "0.44", "-f", "mpeg",
         "-packetsize", str(SECTOR_SIZE), "pipe:1"],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
    )
    if result.returncode:
        print(f"embed_mpeg: ffmpeg failed: {result.stderr.decode(errors='replace').strip()}", file=sys.stderr)
        return 2
    if not result.stdout or len(result.stdout) % SECTOR_SIZE:
        print("embed_mpeg: ffmpeg did not produce whole 2,304-byte Program Stream sectors", file=sys.stderr)
        return 2

    lines = ["/* Generated by embed_mpeg.py; do not edit manually. */\n", f"unsigned char {args.name}[] = {{\n"]
    for offset in range(0, len(result.stdout), 12):
        values = ", ".join(f"0x{byte:02x}" for byte in result.stdout[offset : offset + 12])
        lines.append(f"  {values},\n")
    lines.extend((
        "};\n",
        f"unsigned long {args.name}_len = {len(result.stdout)};\n",
        f"unsigned long {args.name}_period_90k = {period_90k};\n",
    ))
    args.output.write_text("".join(lines))
    print(f"embedded {args.input} as {len(result.stdout) // SECTOR_SIZE} MPEG sectors "
          f"(period {period_90k} ticks) in {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
