#!/usr/bin/env python3
"""Generate a C include containing one pointer for every song sector.

The sequence below is deliberately expressed in sectors, not in loop counts at
runtime.
"""

from pathlib import Path

SECTOR_SIZE = 2304

# (MP2 file, generated C source, symbol, repetitions, first sector)
PARTS = (
    ("start.mp2", "src/sfx_start.c", "start_mpg", 1, 0),
    ("restart.mp2", "src/sfx_restart.c", "restart_mpg", 1, 0),
    ("loop1.mp2", "src/sfx1.c", "loop1_mpg", 4, 0),
    ("loop2.mp2", "src/sfx2.c", "loop2_mpg", 3, 0),
)


def main() -> None:
    lines = ["/* Generated by generate_song_sequence.py; do not edit manually. */\n",
             "static unsigned char *songSequence[] = {\n"]
    count = 0
    repeat_start = 0
    for part_index, (filename, generated_name, symbol, repetitions, skip) in enumerate(PARTS):
        # The intro plays once.  Each subsequent pass starts with restart,
        # then proceeds through the loop groups.
        if part_index == 1:
            repeat_start = count
        if Path(filename).stat().st_size == 0:
            raise ValueError("%s is empty" % filename)
        # Program-stream sectors are determined by embed_mpeg.py.  Read the
        # generated source's length declaration instead of guessing from MP2.
        generated = Path(generated_name).read_text()
        marker = "unsigned long %s_len = " % symbol
        start = generated.index(marker) + len(marker)
        end = generated.index(";", start)
        sectors = int(generated[start:end]) // SECTOR_SIZE
        if skip >= sectors:
            raise ValueError("%s skips all %d sectors" % (filename, sectors))
        for _ in range(repetitions):
            for sector in range(skip, sectors):
                lines.append("    &%s[%d],\n" % (symbol, sector * SECTOR_SIZE))
                count += 1
    lines.extend(("};\n", "#define SONG_SEQUENCE_SECTOR_COUNT %d\n" % count,
                  "#define SONG_SEQUENCE_REPEAT_START %d\n" % repeat_start))
    Path("src/song_sequence.inc").write_text("".join(lines))


if __name__ == "__main__":
    main()
